version: '3'

networks:
  openingwikinet:
    driver: bridge

services:
  postgres:
    image: postgres
    ports:
      - "XXXX:XXXX"
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: ""
      POSTGRES_HOST: "XXXX.XXXX.XXXX.XXXX"
    networks:
      - "openingwikinet"
    restart: on-failure
  redis:
    image: redis
    ports:
      - "XXXX:XXXX"
    networks:
      - "openingwikinet"
  fastapi:
    build:
      context: .
      dockerfile: fastapi.dockerfile
    ports:
      - "XXXX:XXXX"
    depends_on:
      - postgres
      - redis
    networks:
      - "openingwikinet"
